name       : data-default-instances-old-locale
version    : 0.0.1
release    : 3
source     :
    - https://hackage.haskell.org/package/data-default-instances-old-locale-0.0.1/data-default-instances-old-locale-0.0.1.tar.gz : 60d3b02922958c4908d7bf2b24ddf61511665745f784227d206745784b0c0802
license    : BSD-3-Clause
component  : programming.haskell
summary    : Default instances for types in old-locale
description: |
    Default instances for types in old-locale
builddeps  :
    - haskell-cabal-install
    - haskell-data-default-class-devel
    - haskell-old-locale-devel
rundeps    :
    - devel:
        - haskell-data-default-class-devel
        - haskell-old-locale-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
